primaryColor=#7cc8eb
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=abbas.khanezad@gmail.com
loadingLabel=در حال بارگزاری...
loginError=قادر به ورود نیستید
chatHeader=گفتگوی زنده با پشتیبانی دکترپلاس
startInfo=برای شروع گفتگو با واحد پشتیبانی ، لطفا فیلد های زیر را تکمیل کنید
startLabel=شروع
backLabel=بازگشت
initMessageBody=سلام ، می توانم به شما کمک کنم؟
initMessageAuthor=اپراتور
chatInputLabel=پرسش خود را بنویسید
timeDaysAgo=روز قبل
timeHoursAgo=ساعت قبل
timeMinutesAgo=دقیقه قبل
timeSecondsAgo=ثانیه قبل
offlineMessage=اپراتور آفلاین شد.
toggleSoundLabel=افکت صوتی
toggleScrollLabel=اسکرول اتوماتیک
toggleEmoticonsLabel=شکلک ها
toggleAutoShowLabel=نمایش اتوماتیک
contactHeader=ارتباط با ما
contactInfo=تمامی اپراتور ها آفلاین هستند ، شما میتوانید سوال خود را در کادر زیر وارد کنید. در کمترین زمان پاسخ به ایمیل شما ارسال می شود
contactNameLabel=نام شما
contactMailLabel=ایمیل شما
contactQuestionLabel=پرسش شما
contactSendLabel=ارسال
contactSuccessHeader=پیام شما ارسال شد
contactSuccessMessage=پرسش شما با موفقیت ارسال شد. از ارتباط شما متشکریم
contactErrorHeader=خطا
contactErrorMessage=یک خطای نامشخص در هنگام ارسال پرسش رخ داده. لطفا مجددا سعی کنید
maxConnections=5
messageSound=audio/default.mp3
installed=1
